### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by ghost** [1Computer1/megumin-selfbot#8]
This is the error I get when I try to run the self bot. I follow the setup guide and did everything as it told me.

![image](https://user-images.githubusercontent.com/29898563/27909963-5c9e483c-6253-11e7-9b35-6beeccefbebb.png)

**Comment by novara754** [comment]
You are not supposed to use Windows' weird built-in JS thing.
Download and install [Node.js](https://nodejs.org/) and then run it with that.

You can find a detailed guide on how to set up the selfbot [here](https://github.com/1Computer1/megumin-selfbot/blob/master/SETUP.md)
